const $=id=>document.getElementById(id);
let data=null,used=new Set(),current='',turn=0,over=false,wins=0,losses=0,totalTurns=0;
const attack=()=>data?.attackDepth||{};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function candidates(ch){return (data.byFirst[ch]||[]).filter(w=>!used.has(w))}
function saveStats(){localStorage.kkeulStats=JSON.stringify({wins,losses,totalTurns})}
function loadStats(){try{({wins=0,losses=0,totalTurns=0}=JSON.parse(localStorage.kkeulStats||'{}'))}catch{wins=losses=totalTurns=0}updateStats()}
function updateStats(){const g=wins+losses;$('wins').textContent=wins;$('losses').textContent=losses;$('games').textContent=g;$('winrate').textContent=g?Math.round(wins/g*100)+'%':'0%';$('avg').textContent=g?(totalTurns/g).toFixed(1)+'턴':'-'}
function addHistory(who,w){$('history').insertAdjacentHTML('beforeend',`<div class="line"><b>${esc(who)}</b> · ${esc(w)}${attack()[w]!=null?` <span class="attack">(공격 깊이 ${attack()[w]})</span>`:''}</div>`);$('history').scrollTop=$('history').scrollHeight}
function start(){used.clear();over=false;turn=0;$('history').innerHTML='';$('singleInput').disabled=$('singleSend').disabled=false;let pool=data.startPool;current=pool[Math.floor(Math.random()*pool.length)];used.add(current);$('startWord').value=current;$('last').textContent=current.at(-1);$('turn').textContent=0;$('depth').textContent=attack()[current]??'-';$('message').textContent=`시작 단어는 '${current}'. '${current.at(-1)}'로 시작하는 단어를 입력해!`;addHistory('시작',current);$('singleInput').focus()}
function finish(ai){over=true;$('singleInput').disabled=$('singleSend').disabled=true;if(ai)wins++;else losses++;totalTurns+=turn;saveStats();updateStats();$('message').textContent=ai?'AI 승리!':'플레이어 승리!'}
function score(w,lv){const d=attack()[w]??99,n=candidates(w.at(-1)).length;let s=(100-d)*5+Math.max(0,40-n)+Math.min(20,w.length*2);if(lv>=4)s+=Math.random()*3;return s}
function aiPick(){const lv=+$('difficulty').value,c=candidates(current.at(-1));if(!c.length){finish(false);return null}if(lv===5){const immediate=c.filter(w=>candidates(w.at(-1)).length===0);if(immediate.length)return immediate.sort((a,b)=>(attack()[a]??999)-(attack()[b]??999))[0];const a=c.filter(w=>attack()[w]!=null);if(a.length)return a.sort((x,y)=>(attack()[x]??999)-(attack()[y]??999))[0]}let a=lv<5?c.filter(w=>attack()[w]==null):c;if(!a.length)a=c;if(lv===1)return a[Math.floor(Math.random()*a.length)];a.sort((x,y)=>score(y,lv)-score(x,lv));if(lv===2)return a[Math.floor(Math.random()*Math.min(10,a.length))];if(lv===3)return a[Math.floor(Math.random()*Math.min(4,a.length))];return a[0]}
function aiTurn(){if(over)return;const w=aiPick();if(!w)return;used.add(w);current=w;turn++;$('last').textContent=w.at(-1);$('turn').textContent=turn;$('depth').textContent=attack()[w]??'-';addHistory('AI',w);if(!candidates(w.at(-1)).length){finish(true);return}$('message').textContent=`AI: ${w} → '${w.at(-1)}'`;$('singleInput').disabled=$('singleSend').disabled=false;$('singleInput').focus()}
function submit(){if(over)return;const w=$('singleInput').value.trim();$('singleInput').value='';if(!w)return;if(!data.wordSet[w])return $('message').textContent='목록에 없는 단어야.';if(used.has(w))return $('message').textContent='이미 나온 단어야.';if(w[0]!==current.at(-1))return $('message').textContent=`'${current.at(-1)}'로 시작해야 해.`;used.add(w);current=w;turn++;$('last').textContent=w.at(-1);$('turn').textContent=turn;$('depth').textContent=attack()[w]??'-';addHistory('나',w);if(!candidates(w.at(-1)).length)return finish(false);$('singleInput').disabled=$('singleSend').disabled=true;$('message').textContent='AI가 생각 중...';setTimeout(aiTurn,250)}
$('singleSend').onclick=submit;$('singleInput').onkeydown=e=>{if(e.key==='Enter')submit()};$('restart').onclick=start;$('newStart').onclick=start;$('difficulty').onchange=()=>{};
async function loadData(){const r=await fetch('/api/data');data=await r.json();data.wordSet=Object.fromEntries(data.words.map(w=>[w,true]));data.byFirst={};for(const w of data.words)(data.byFirst[w[0]]??=[]).push(w);loadStats();start()}
// Server sends the full official dataset. Kept as a single request so the browser never invents words.
const socket=io();let room=null,myId=null;
function roomRender(s){room=s;$('roomInfo').innerHTML=`<b>방 코드: ${s.roomCode}</b><br>플레이어: ${s.players.map(p=>esc(p.name)+' (P'+p.slot+')').join(' · ')||'-'}<br>현재 차례: ${s.turnPlayer?(s.players.find(p=>p.id===s.turnPlayer)?.name||'-'):'대기 중'}`;$('startOnline').classList.toggle('hidden',!(s.players[0]?.id===myId&&!s.started&&s.players.length===2))}
socket.on('connect',()=>myId=socket.id);socket.on('room_created',x=>{$('roomCode').value=x.code;$('onlineMessage').textContent='방이 만들어졌어. 친구에게 코드를 알려줘.'});socket.on('room_state',roomRender);socket.on('notice',m=>$('onlineMessage').textContent=m);socket.on('error_msg',m=>$('onlineMessage').textContent=m);socket.on('game_started',x=>{$('onlineHistory').innerHTML='';$('onlineMessage').textContent=`게임 시작! 시작 단어: ${x.startWord}`;onlineLast=x.startWord;onlineTurn=x.state.turnPlayer;onlineStarted=true;addOnline('시작',x.startWord,x.state.lastDepth);roomRender(x.state)});let onlineLast='',onlineTurn=null,onlineStarted=false;
function addOnline(who,w,d){$('onlineHistory').insertAdjacentHTML('beforeend',`<div class="line"><b>${esc(who)}</b> · ${esc(w)}${d!=null?` <span class="attack">(공격 깊이 ${d})</span>`:''}</div>`);$('onlineHistory').scrollTop=$('onlineHistory').scrollHeight}
socket.on('word_played',x=>{onlineLast=x.word;onlineTurn=x.state.turnPlayer;addOnline(x.playerId===myId?'나':(x.state.players.find(p=>p.id===x.playerId)?.name||'상대'),x.word,x.depth);roomRender(x.state);$('onlineMessage').textContent=x.state.turnPlayer===myId?'내 차례야.':'상대방 차례야.'});socket.on('game_over',x=>{$('onlineMessage').textContent=x.winner===myId?'온라인 승리!':'온라인 패배!';onlineStarted=false});
$('create').onclick=()=>socket.emit('create_room',{name:$('name').value.trim()||'Player'});$('join').onclick=()=>socket.emit('join_room',{code:$('roomCode').value,name:$('name').value.trim()||'Player'});$('startOnline').onclick=()=>socket.emit('start_online');$('onlineSend').onclick=()=>onlineSubmit();$('onlineInput').onkeydown=e=>{if(e.key==='Enter')onlineSubmit()};function onlineSubmit(){if(!onlineStarted||onlineTurn!==myId)return;$('onlineInput').value&&(socket.emit('play_word',{word:$('onlineInput').value.trim()}),$('onlineInput').value='')}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('single').classList.toggle('hidden',b.dataset.mode!=='single');$('online').classList.toggle('hidden',b.dataset.mode!=='online')});
loadData();
